PENDING: serial: qcom-geni: Enable Serial on SA8255p platform
JIRA: https://issues.redhat.com/browse/VROOM-33528
Upstream-status: https://git.codelinaro.org/clo/le/meta-qti-auto-kernel/-/blob/LY.AU.0.1.0.r1-16800-gen4meta.0/recipes-kernel/linux/files/qup/0002-PENDING-serial-qcom-geni-Enable-Serial-on-SA8255p-pl.patch
References: https://git.codelinaro.org/clo/la/kernel/qcom.git
Conflicts:
  - in qcom_geni_serial_remove() due to the BSP tree missing upstream
    commit dd4d4497be8f ("serial: qcom_geni: Convert to platform remove
    callback returning void")

Note:
    Upstream commit fa103d2599e1 ("serial: qcom-geni: fix receiver enable")
    removes the qcom_geni_serial_stop_rx()/qcom_geni_serial_start_rx()
    calls in qcom_geni_serial_set_termios(). The BSP kernel, which is
    based on stable v6.6.65, has this commit as 647cd4494cc3. The ported
    patch comes on top of that, and re-adds the two calls without
    explaining why. Keeping them, as it seems to be the intention, since
    the commit that removed them was already in the history. This was
    reconciled automatically by git cherry-pick and did NOT generate a
    conflict.

Fixed compile errors:
drivers/tty/serial/qcom_geni_serial.c:1306:25: error: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long unsigned int’ [-Werror=format=]
 1306 |                         "Couldn't find suitable clock rate for %u\n",
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/tty/serial/qcom_geni_serial.c:1311:31: error: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘long unsigned int’ [-Werror=format=]
 1311 |         dev_dbg(port->se.dev, "desired_rate = %u, clk_rate = %lu, clk_div = %u\n",
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/tty/serial/qcom_geni_serial.c:1345:28: error: unused variable ‘opp’ [-Werror=unused-variable]
 1345 |         struct dev_pm_opp *opp;
      |                            ^~~
drivers/tty/serial/qcom_geni_serial.c:1354:34: error: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Werror=format=]
 1354 |                 dev_err(se->dev, "performance operation(%d) failed with err=%d\n",
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Author: Praveen Talari <quic_ptalari@quicinc.com>
Date:   Wed Jul 17 19:28:51 2024 +0530

    Enable or disable resources such as clocks, interconnect
    paths, and TLMM (GPIOs) via the logical power domain,
    invoked as part of geni_spi_transition_d3d0 where d0 is on
    and d3 is off states.

    The bandrate is handle through perf domain with help
    of perf levels and we are directly passing baudrate value
    as perf level using dev_pm_opp_set_level().

    Change-Id: Ide3e59ccb35baf674cd45a75e903be4c0e97979e
    Signed-off-by: Praveen Talari <quic_ptalari@quicinc.com>
    Signed-off-by: Nikunj Kela <quic_nkela@quicinc.com>
    Signed-off-by: Shazad Hussain <quic_shazhuss@quicinc.com>

Signed-off-by: Radu Rendec <rrendec@redhat.com>